name: Freewave iOS Build
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'App version'
        required: true
        default: '1.0.0'
# Adding explicit permissions
permissions:
  contents: write
jobs:
  build-ios:
    name: 🌊 Freewave iOS Build
    runs-on: macos-latest
    steps:
      - name: Checkout Freewave repository
        uses: actions/checkout@v3
        
      - name: Setup Flutter environment
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
          
      - name: Install Flutter dependencies
        run: flutter pub get
        
      - name: Update CocoaPods repository
        run: pod repo update
        working-directory: ios
        
      - name: Build Freewave iOS app
        run: flutter build ios --release --no-codesign
      
      - name: Create Payload directory
        run: mkdir -p Payload
        working-directory: build/ios/iphoneos
        
      - name: Move app to Payload directory
        run: mv Runner.app Payload/
        working-directory: build/ios/iphoneos
        
      - name: Create IPA file
        run: zip -qq -r Freewave.ipa Payload
        working-directory: build/ios/iphoneos
        
      - name: Verify IPA file exists
        run: ls -lh build/ios/iphoneos/
        
      - name: Create builds directory
        run: mkdir -p builds
        
      - name: Copy IPA to builds directory
        run: cp build/ios/iphoneos/Freewave.ipa builds/Freewave-${{ github.event.inputs.version }}.ipa
        
      - name: Commit and push IPA file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add builds/Freewave-${{ github.event.inputs.version }}.ipa
          git commit -m "Add iOS build v${{ github.event.inputs.version }}"
          git push
